export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "ocean-blue": "#3394DE",
        "surface-tint": "#00629d",
        "inverse-on-surface": "#f1f1f1",
        "error": "#ba1a1a",
        "tertiary-container": "#667590",
        "error-container": "#ffdad6",
        "outline-variant": "#bfc7d2",
        "on-primary-container": "#fdfcff",
        "surface-bright": "#f9f9f9",
        "on-surface-variant": "#404751",
        "surface-container-highest": "#e2e2e2",
        "background": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "snow-white": "#FFFFFF",
        "on-error-container": "#93000a",
        "midnight-navy": "#28374F",
        "on-surface": "#1a1c1c",
        "on-tertiary-fixed-variant": "#384760",
        "secondary": "#b81d2c",
        "tertiary-fixed": "#d5e3ff",
        "on-secondary": "#ffffff",
        "slate-gray": "#64748B",
        "surface-variant": "#e2e2e2",
        "on-primary-fixed-variant": "#004a77",
        "on-error": "#ffffff",
        "primary-container": "#007ac0",
        "primary-fixed": "#cfe5ff",
        "sunset-red": "#DF3C44",
        "inverse-primary": "#98cbff",
        "surface-container": "#eeeeee",
        "secondary-fixed": "#ffdad8",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed": "#0b1c32",
        "on-secondary-fixed-variant": "#93001a",
        "primary-fixed-dim": "#98cbff",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed": "#410006",
        "tertiary-fixed-dim": "#b8c7e5",
        "on-secondary-container": "#5b000c",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-container": "#fefcff",
        "secondary-fixed-dim": "#ffb3b0",
        "on-primary-fixed": "#001d33",
        "primary": "#006099",
        "outline": "#707882",
        "on-tertiary": "#ffffff",
        "surface": "#f9f9f9",
        "secondary-container": "#ff5358",
        "surface-dim": "#dadada",
        "tertiary": "#4e5d76",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Open Sans", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Open Sans", "sans-serif"],
        "headline-xl-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Open Sans", "sans-serif"],
        "body-sm": ["Open Sans", "sans-serif"],
        "price-tag": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "price-tag": ["22px", { "lineHeight": "24px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
