export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf9f9",
        "surface-dim": "#dbdada",
        "surface-bright": "#faf9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#e9e8e8",
        "surface-container-highest": "#e3e2e2",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#5b4137",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f2f0f0",
        "outline": "#8f7065",
        "outline-variant": "#e3bfb1",
        "surface-tint": "#a63c00",
        "primary": "#a63c00",
        "on-primary": "#ffffff",
        "primary-container": "#ff6000",
        "on-primary-container": "#531a00",
        "inverse-primary": "#ffb598",
        "secondary": "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e4e2e2",
        "on-secondary-container": "#656464",
        "tertiary": "#0061a4",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#0098fd",
        "on-tertiary-container": "#002e53",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbce",
        "primary-fixed-dim": "#ffb598",
        "on-primary-fixed": "#370e00",
        "on-primary-fixed-variant": "#7e2c00",
        "secondary-fixed": "#e4e2e2",
        "secondary-fixed-dim": "#c8c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474747",
        "tertiary-fixed": "#d1e4ff",
        "tertiary-fixed-dim": "#9fcaff",
        "on-tertiary-fixed": "#001d36",
        "on-tertiary-fixed-variant": "#00497d",
        "background": "#faf9f9",
        "on-background": "#1b1c1c",
        "surface-variant": "#e3e2e2",
        "background-subtle": "#F5F5F5",
        "surface-white": "#FFFFFF",
        "success-green": "#27AE60",
        "error-red": "#E74C3C",
        "border-light": "#E2E2E2"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "12px",
        "margin-mobile": "16px",
        "margin-desktop": "auto",
        "max-width": "1280px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "price-display": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "price-display": ["22px", { "lineHeight": "22px", "fontWeight": "700" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
