export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdad8",
        "surface-dim": "#f1d3d2",
        "primary-container": "#db313f",
        "secondary-fixed": "#d5e3ff",
        "surface-container": "#ffe9e8",
        "on-primary": "#ffffff",
        "tertiary": "#565e55",
        "inverse-primary": "#ffb3b1",
        "secondary-container": "#bbd3fd",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#dce5d9",
        "on-tertiary-fixed-variant": "#404940",
        "secondary": "#485f84",
        "surface": "#fff8f7",
        "on-surface": "#271717",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-variant": "#f9dcda",
        "on-primary-fixed-variant": "#92001c",
        "surface-container-highest": "#f9dcda",
        "on-surface-variant": "#5b403f",
        "surface-container-high": "#ffe1e0",
        "on-secondary-container": "#445a7f",
        "surface-container-low": "#fff0ef",
        "surface-bright": "#fff8f7",
        "primary": "#b7102a",
        "outline": "#8f6f6e",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#410007",
        "on-tertiary-container": "#f6fff3",
        "secondary-fixed-dim": "#b0c7f1",
        "background": "#fff8f7",
        "primary-fixed-dim": "#ffb3b1",
        "surface-tint": "#bb152c",
        "inverse-on-surface": "#ffedeb",
        "on-secondary-fixed-variant": "#30476a",
        "on-tertiary-fixed": "#161d16",
        "on-background": "#271717",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#3e2c2b",
        "on-secondary-fixed": "#001b3c",
        "tertiary-fixed-dim": "#c0c9be",
        "outline-variant": "#e4bebc",
        "error-container": "#ffdad6",
        "tertiary-container": "#6e776d",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "unit": "4px",
        "sm": "8px",
        "xxl": "96px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "lg": "24px",
        "xl": "48px",
        "md": "16px",
        "xs": "4px"
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["Geist"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-md": ["Geist"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.1", "fontWeight": "700"}],
        "headline-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.0", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "display-lg": ["80px", {"lineHeight": "1.0", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "label-md": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
