export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c4c6d2",
        "on-error-container": "#93000a",
        "on-secondary-container": "#00355c",
        "primary": "#24389c",
        "on-primary-fixed": "#00105c",
        "surface": "#fcf9f8",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#cfd2dd",
        "secondary-fixed-dim": "#9ecaff",
        "primary-container": "#3f51b5",
        "tertiary-fixed": "#e0e2ee",
        "tertiary": "#3f434c",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c5c5d4",
        "on-secondary": "#ffffff",
        "inverse-surface": "#303030",
        "on-background": "#1b1c1c",
        "on-secondary-fixed-variant": "#00497d",
        "surface-variant": "#e5e2e1",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container-high": "#eae7e7",
        "secondary-fixed": "#d1e4ff",
        "surface-container": "#f0eded",
        "surface-tint": "#4355b9",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#293ca0",
        "on-tertiary-fixed": "#181b24",
        "surface-container-highest": "#e5e2e1",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-container": "#cacfff",
        "surface-bright": "#fcf9f8",
        "on-tertiary-fixed-variant": "#434750",
        "primary-fixed": "#dee0ff",
        "on-surface-variant": "#454652",
        "surface-dim": "#dcd9d9",
        "tertiary-container": "#575a64",
        "outline": "#757684",
        "inverse-primary": "#bac3ff",
        "primary-fixed-dim": "#bac3ff",
        "background": "#fcf9f8",
        "on-secondary-fixed": "#001d36",
        "secondary": "#0061a4",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#33a0fd",
        "on-surface": "#1b1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "base": "4px",
        "md": "16px",
        "container-margin": "16px",
        "gutter": "12px",
        "lg": "24px",
        "sm": "8px",
        "xl": "32px"
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "button": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
