/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#6900b3',
        'on-background': '#191c1e',
        'surface-dim': '#d8dadc',
        'primary-fixed-dim': '#c6c6cc',
        'surface-bright': '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'on-secondary-container': '#fffbff',
        'primary': '#000000',
        'surface-container-highest': '#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#1a1c20',
        'tertiary-container': '#2c0051',
        'secondary-fixed': '#e1e0ff',
        'tertiary-fixed': '#f0dbff',
        'background': '#f7f9fb',
        'on-surface': '#191c1e',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed': '#2c0051',
        'error': '#ba1a1a',
        'inverse-on-surface': '#eff1f3',
        'on-primary': '#ffffff',
        'on-primary-container': '#828489',
        'secondary-fixed-dim': '#c0c1ff',
        'secondary': '#4648d4',
        'on-tertiary-container': '#ac59fb',
        'on-error': '#ffffff',
        'outline-variant': '#c6c6cb',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#45474b',
        'on-secondary-fixed-variant': '#2f2ebe',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#e2e2e8',
        'secondary-container': '#6063ee',
        'surface-tint': '#5d5e63',
        'surface-container-high': '#e6e8ea',
        'inverse-primary': '#c6c6cc',
        'tertiary': '#000000',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#ddb7ff',
        'outline': '#76777b',
        'surface': '#f7f9fb',
        'surface-variant': '#e0e3e5',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#07006c',
        'surface-container': '#eceef0',
        'primary-container': '#1a1c20',
        'on-surface-variant': '#45474b',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'section-gap': '120px',
        'stack-lg': '32px',
        'margin-mobile': '20px',
        'container-max': '1280px',
        'stack-sm': '8px',
        'gutter': '24px',
        'margin-desktop': '64px',
        'stack-md': '16px',
      },
      fontFamily: {
        'display-lg': ['Montserrat', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'display-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-xl': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'display-lg-mobile': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
