/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f5",
        "surface-dim": "#dcdad6",
        "surface-bright": "#fcf9f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ef",
        "surface-container": "#f0ede9",
        "surface-container-high": "#ebe8e4",
        "surface-container-highest": "#e5e2de",
        "on-surface": "#1c1c1a",
        "on-surface-variant": "#49454a",
        "inverse-surface": "#31302e",
        "inverse-on-surface": "#f3f0ec",
        "outline": "#7a767b",
        "outline-variant": "#cbc5ca",
        "surface-tint": "#615d63",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1d1a1f",
        "on-primary-container": "#888288",
        "inverse-primary": "#cbc4cb",
        "secondary": "#b71319",
        "on-secondary": "#ffffff",
        "secondary-container": "#db322f",
        "on-secondary-container": "#fffbff",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#121e15",
        "on-tertiary-container": "#79877b",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e8e0e7",
        "primary-fixed-dim": "#cbc4cb",
        "on-primary-fixed": "#1d1a1f",
        "on-primary-fixed-variant": "#49454b",
        "secondary-fixed": "#ffdad6",
        "secondary-fixed-dim": "#ffb4ab",
        "on-secondary-fixed": "#410002",
        "on-secondary-fixed-variant": "#93000d",
        "tertiary-fixed": "#d7e6d8",
        "tertiary-fixed-dim": "#bbcabc",
        "on-tertiary-fixed": "#121e15",
        "on-tertiary-fixed-variant": "#3d4a3f",
        "background": "#fcf9f5",
        "on-background": "#1c1c1a",
        "surface-variant": "#e5e2de",
        "warm-cream": "#F6F3EF",
        "pure-white": "#FFFFFF",
        "charcoal-black": "#1C191E",
        "heritage-red": "#E93C37",
        "forest-accent": "#2D3A30",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "base": "8px",
        "section-gap-desktop": "120px",
        "section-gap-mobile": "64px",
        "grid-margin-desktop": "80px",
        "grid-margin-mobile": "20px",
        "gutter": "24px",
      },
      fontFamily: {
        "display-lg": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "label-lg": ["DM Sans", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "500" }],
        "headline-lg-mobile": ["36px", { "lineHeight": "44px", "fontWeight": "500" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
      },
    },
  },
  plugins: [],
}
