/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bfc7d1",
        "surface-tint": "#006399",
        "background": "#f8ffbd",
        "surface-container-high": "#e6edad",
        "on-tertiary-fixed-variant": "#004f59",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "secondary-container": "#dfe0e0",
        "inverse-on-surface": "#eff6b5",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#404850",
        "inverse-primary": "#94ccff",
        "on-secondary-container": "#616363",
        "on-background": "#1a1e00",
        "primary-fixed": "#cde5ff",
        "primary": "#005d90",
        "on-primary-fixed": "#001d32",
        "on-tertiary-fixed": "#001f24",
        "primary-container": "#0077b6",
        "on-primary-container": "#f3f7ff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#e7fbff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c6c6c7",
        "surface": "#f8ffbd",
        "surface-bright": "#f8ffbd",
        "surface-container-highest": "#e1e8a8",
        "tertiary-container": "#227c8a",
        "tertiary-fixed": "#9feffe",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#83d3e1",
        "on-secondary-fixed-variant": "#454747",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#1a1c1c",
        "secondary": "#5d5f5f",
        "inverse-surface": "#2e3305",
        "outline": "#707881",
        "primary-fixed-dim": "#94ccff",
        "tertiary": "#00626f",
        "on-primary-fixed-variant": "#004b74",
        "secondary-fixed": "#e2e2e2",
        "surface-variant": "#e1e8a8",
        "surface-container": "#ecf3b3",
        "surface-container-low": "#f2f9b8",
        "surface-dim": "#d8dfa0",
        "on-surface": "#1a1e00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "circle": "9999px"
      },
      spacing: {
        "container-margin": "20px",
        "xl": "64px",
        "sm": "16px",
        "gutter": "16px",
        "xs": "8px",
        "base": "4px",
        "md": "24px",
        "lg": "40px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "30px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
