/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2f3131",
        "on-primary-fixed-variant": "#3c4d00",
        "on-error": "#690005",
        "background": "#121414",
        "on-surface-variant": "#c4c9ac",
        "on-secondary": "#313030",
        "tertiary": "#ffffff",
        "primary-fixed": "#c3f400",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-low": "#1a1c1c",
        "surface-container-highest": "#333535",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#1b1b1c",
        "surface-container-lowest": "#0c0f0f",
        "surface-container": "#1e2020",
        "surface-variant": "#333535",
        "surface": "#121414",
        "on-secondary-container": "#bab8b7",
        "secondary-fixed": "#e5e2e1",
        "outline": "#8e9379",
        "on-error-container": "#ffdad6",
        "outline-variant": "#444933",
        "on-surface": "#e2e2e2",
        "primary": "#ffffff",
        "inverse-primary": "#506600",
        "primary-container": "#c3f400",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary": "#303030",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#474646",
        "surface-tint": "#abd600",
        "on-tertiary-container": "#656464",
        "on-primary": "#283500",
        "on-background": "#e2e2e2",
        "primary-fixed-dim": "#abd600",
        "secondary": "#c8c6c5",
        "surface-dim": "#121414",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-surface": "#e2e2e2",
        "on-primary-fixed": "#161e00",
        "secondary-container": "#4a4949",
        "surface-container-high": "#282a2b",
        "on-primary-container": "#556d00",
        "surface-bright": "#37393a",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474746",
        "tertiary-container": "#e5e2e1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "base": "8px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-margin-mobile": "16px",
        "container-margin-desktop": "40px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
