/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#00346f',
        'primary-container': '#004a99',
        'on-primary': '#ffffff',
        'on-primary-container': '#9bbdff',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#abc7ff',
        'on-primary-fixed': '#001b3f',
        'on-primary-fixed-variant': '#00458f',
        'inverse-primary': '#abc7ff',
        'secondary': '#705d00',
        'secondary-container': '#fcd400',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6e5c00',
        'secondary-fixed': '#ffe16d',
        'secondary-fixed-dim': '#e9c400',
        'on-secondary-fixed': '#221b00',
        'on-secondary-fixed-variant': '#544600',
        'tertiary': '#323537',
        'tertiary-container': '#494c4e',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#babcbe',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-fixed-variant': '#444749',
        'background': '#f9f9ff',
        'on-background': '#111c2d',
        'surface': '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#d8e3fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'surface-tint': '#255dad',
        'on-surface': '#111c2d',
        'on-surface-variant': '#424751',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'outline': '#737783',
        'outline-variant': '#c2c6d3',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'price-display': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '48px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'max-width': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
