export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#73603b",
        "secondary-fixed": "#f9dfb1",
        "surface-variant": "#e3e3df",
        "on-primary-fixed-variant": "#474746",
        "surface-container": "#eeeeea",
        "on-primary-fixed": "#1c1b1b",
        "inverse-surface": "#2f312e",
        "tertiary-container": "#1a1c19",
        "on-background": "#1a1c1a",
        "tertiary-fixed-dim": "#c6c7c2",
        "on-primary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "secondary": "#6e5c37",
        "primary-fixed-dim": "#c8c6c5",
        "surface-dim": "#dadad6",
        "outline": "#747878",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#261a00",
        "surface-bright": "#faf9f5",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#838480",
        "on-primary-container": "#858383",
        "secondary-container": "#f6ddae",
        "error": "#ba1a1a",
        "primary-container": "#1c1b1b",
        "on-tertiary-fixed": "#1a1c19",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e3e3de",
        "secondary-fixed-dim": "#dcc497",
        "on-surface-variant": "#444748",
        "surface-container-high": "#e8e8e4",
        "on-surface": "#1a1c1a",
        "background": "#faf9f5",
        "on-secondary-fixed-variant": "#554422",
        "surface-container-highest": "#e3e3df",
        "inverse-primary": "#c8c6c5",
        "error-container": "#ffdad6",
        "outline-variant": "#c4c7c7",
        "tertiary": "#000000",
        "primary": "#000000",
        "on-tertiary-fixed-variant": "#454744",
        "surface": "#faf9f5",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f1ed",
        "primary-fixed": "#e5e2e1",
        "surface-container-low": "#f4f4f0"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "24px",
        "container-max": "1440px",
        "section-gap": "128px",
        "gutter": "32px",
        "margin-desktop": "64px",
        "unit": "8px"
      },
      fontFamily: {
        "body-lg": ["Metrophobic"],
        "headline-md": ["Libre Caslon Text"],
        "body-md": ["Metrophobic"],
        "headline-lg": ["Libre Caslon Text"],
        "display-lg-mobile": ["Libre Caslon Text"],
        "display-lg": ["Libre Caslon Text"],
        "label-caps": ["Metrophobic"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "56px", "fontWeight": "400"}],
        "display-lg-mobile": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "400"}],
        "display-lg": ["80px", {"lineHeight": "90px", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
